name = "lamp-delivery"
main = "dist/_worker.js/index.js"
compatibility_date = "2026-05-30"
type = "javascript"
# Replace CF_ACCOUNT_ID_PLACEHOLDER with your Cloudflare Account ID in CI or locally
account_id = "CF_ACCOUNT_ID_PLACEHOLDER"
routes = [
  { pattern = "lamp.delivery/*", zone_name = "lamp.delivery" },
  { pattern = "www.lamp.delivery/*", zone_name = "lamp.delivery" }
]

[vars]
# add any worker-level environment variables here
